/**
 * ESLint Configuration — Flat Config Format (ESLint 9+)
 *
 * ESLint is a static analysis tool that finds problems in your JavaScript/TypeScript
 * code before you run it. Think of it as a spell-checker for code — it catches common
 * mistakes like unused variables, missing imports, or React Hook rule violations.
 *
 * ESLint 9 introduced "flat config" — a simpler configuration format that replaces
 * the old `.eslintrc.*` cascade. Instead of multiple config files that merge in
 * confusing ways, you have one `eslint.config.js` that exports an array of config
 * objects. Each object can target specific files and apply specific rules.
 *
 * We use `eslint-config-expo`, Expo's official shareable config for SDK 54+.
 * Under the hood, it bundles these plugins and their recommended rules:
 *   - @typescript-eslint — TypeScript-specific linting (no-unused-vars, type safety)
 *   - eslint-plugin-react — React best practices (JSX rules, component patterns)
 *   - eslint-plugin-react-hooks — Enforces Rules of Hooks (deps arrays, call order)
 *   - eslint-plugin-import — Ensures imports resolve correctly, no cycles
 *   - eslint-plugin-expo — Expo-specific rules (API usage, SDK compatibility)
 *
 * This means we get a well-tested, comprehensive ruleset without manually
 * configuring dozens of individual rules — Expo maintains it for us.
 */

// Import the Expo config in flat-config format.
// The `/flat` suffix tells eslint-config-expo to export an array of flat config
// objects instead of the legacy format.
const expoConfig = require("eslint-config-expo/flat");

module.exports = [
  // Spread the Expo config — this is an array of config objects that set up
  // the parser (@typescript-eslint/parser), all the plugins listed above,
  // and their recommended rule presets.
  ...expoConfig,

  // Our project-specific overrides go in a separate config object.
  // In flat config, later objects in the array take precedence over earlier ones,
  // so our ignores and rules here override the Expo defaults where needed.
  {
    // `ignores` tells ESLint to completely skip these paths.
    // This is the flat-config equivalent of the old `.eslintignore` file.
    ignores: [
      "dist/*", // Expo build output — generated code, not ours to lint
      "lib/types/database.types.ts", // Auto-generated by `supabase gen types` — will be overwritten
      "supabase/functions/**", // Deno Edge Functions — use npm: specifiers that eslint-plugin-import can't resolve
    ],
  },
];
