/**
 * Admin Billing Dashboard Screen
 *
 * Displays gym billing information for gym admins:
 *   1. Current month widget — live active user count + projected bill
 *   2. Billing history — FlatList of past billing records
 *
 * DATA FLOW:
 *   1. useBilling(gymId) → billingService → PostgREST + RPC
 *      → Postgres (RLS: gym_admin/super_admin policy)
 *   2. Billing records are read-only — no mutations needed since
 *      records are generated by the monthly pg_cron job.
 *
 * STATES:
 *   - Loading: centered ActivityIndicator
 *   - Empty: "No billing history yet" message (new gym, no months billed)
 *   - Data: current month widget + FlatList of past records
 *   - Error: error message
 *
 * NOTE: gymId is currently hardcoded as a placeholder. In production,
 * it will come from the admin's gym context (navigation params or
 * a gym selector in the admin layout).
 */

import React from "react";
import { View, Text, FlatList, ActivityIndicator } from "react-native";
import { useBilling } from "@/hooks/useBilling";
import { GYM_BILLING_RATE_EUR } from "@/lib/constants";

/**
 * Formats a date string (YYYY-MM-DD) into a human-readable month label.
 * e.g., "2026-01-01" → "Jan 2026"
 */
function formatPeriod(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", {
    month: "short",
    year: "numeric",
  });
}

/**
 * Maps billing status to a display color for the status badge.
 * Using semantic colors that match the existing badge patterns:
 *   pending  → amber/warning
 *   invoiced → blue/info
 *   paid     → green/success
 */
function statusColor(status: string): string {
  switch (status) {
    case "paid":
      return "bg-green-600";
    case "invoiced":
      return "bg-blue-600";
    default:
      return "bg-amber-500";
  }
}

export default function BillingScreen() {
  // TODO: Replace with actual gym ID from admin context/navigation params.
  // For now, this serves as the hook integration point.
  const gymId = null;

  const { billingHistory, activeUsers, projectedBill, isLoading, error } =
    useBilling(gymId);

  // ── Loading state ────────────────────────────────────────────────
  if (isLoading) {
    return (
      <View
        className="flex-1 items-center justify-center bg-background"
        testID="loading-indicator"
      >
        <ActivityIndicator size="large" color="#6366f1" />
      </View>
    );
  }

  // ── Error state ──────────────────────────────────────────────────
  if (error) {
    return (
      <View className="flex-1 items-center justify-center bg-background px-4">
        <Text className="text-error text-center">
          {error.message || "Failed to load billing data"}
        </Text>
      </View>
    );
  }

  // ── Empty state ──────────────────────────────────────────────────
  if (billingHistory.length === 0 && activeUsers === 0) {
    return (
      <View
        className="flex-1 items-center justify-center bg-background"
        testID="empty-state"
      >
        <Text className="text-text-secondary text-center text-base">
          No billing history yet
        </Text>
      </View>
    );
  }

  // ── Billing dashboard ────────────────────────────────────────────
  return (
    <View className="flex-1 bg-background" testID="billing-screen">
      <Text className="text-xl font-bold text-text-primary px-4 pt-4 pb-2">
        Billing
      </Text>

      {/* Current month projection widget */}
      <View className="mx-4 mb-4 bg-surface rounded-lg p-4" testID="current-month-widget">
        <Text className="text-text-secondary text-sm mb-1">
          Current Month
        </Text>
        <Text className="text-text-primary text-lg font-semibold">
          {activeUsers} active user{activeUsers !== 1 ? "s" : ""}
        </Text>
        <Text className="text-text-secondary text-sm mt-1">
          Projected: €{projectedBill.toFixed(2)} (€
          {GYM_BILLING_RATE_EUR.toFixed(2)}/user)
        </Text>
      </View>

      {/* Billing history list */}
      <FlatList
        data={billingHistory}
        keyExtractor={(item: any) => item.id}
        contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 24 }}
        renderItem={({ item }: { item: any }) => (
          <View className="bg-surface rounded-lg p-4 mb-3">
            {/* Period + status badge */}
            <View className="flex-row items-center justify-between mb-2">
              <Text className="text-text-primary font-medium">
                {formatPeriod(item.period_start)}
              </Text>
              <View className={`px-2 py-0.5 rounded-full ${statusColor(item.status)}`}>
                <Text className="text-white text-xs font-medium capitalize">
                  {item.status}
                </Text>
              </View>
            </View>

            {/* Active users + total due */}
            <Text className="text-text-secondary text-sm">
              {item.active_user_count} active user
              {item.active_user_count !== 1 ? "s" : ""} · €
              {parseFloat(item.total_due_eur).toFixed(2)}
            </Text>
          </View>
        )}
      />
    </View>
  );
}
